fix(tags): fix inheritance according to cucumber specs
TheBrainFamily/cypress-cucumber-preprocessor pull request #557
Opened 2021-04-28 15:56 UTC by Sonaryr

According to cucumber tags should be inherited downwards. See
https://cucumber.io/docs/cucumber/api/#tags

fix #196

2021-06-02 07:49 UTC, lgandecki commented
@MateuszNowosad could you please verify and merge if this looks good?

2021-06-02 08:16 UTC, MateuszNowosad commented
I will test this today.

2021-06-02 17:05 UTC, MateuszNowosad requested changes
From what I can see this follows the existing pattern used in creating tests from scenarios. I wasn't able to break it, everything seems to be working correctly. I've also run commented out tests from BeforeAndAfterSteps and BailOnStepFailure just to be sure. 

I've put forward some suggestions for @Sonaryr to look at before merging. Maybe I will come up with something that might need fixing tomorrow but if not this will be ready for a merge.

2021-06-07 11:52 UTC, MateuszNowosad reviewed
@Sonaryr Sorry, it took me a few days to re-review this. The current state of this PR is satisfactory however, while I was testing this I noticed some issues. 

While having e.g. test structure like:

```
@all
Feature
    
    @tag1
    Scenario Outline: I order <product> 

        @tag2
        Examples:
        
        @tag3
        Examples:
```

if you were to try:
`./node_modules/.bin/cypress-tags run -e TAGS='@all and @tag2'`

No test would actually run because [cypress-tags.js](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/b9804ce4a647310320bd4f17b42391f8b46cfe07/cypress-tags.js) file was not changed to accommodate Example tagging. This issue was raised in #489. 

There would have to be some changes made to this file, somewhere near 85-100 line;

```
const featureTags = parsedFeature.feature.tags;
  const featureShouldRun = shouldProceedCurrentStep(featureTags, envTags);
  const taggedScenarioShouldRun = parsedFeature.feature.children.some(
    (section) =>
      section.tags &&
      section.tags.length &&
      shouldProceedCurrentStep(section.tags.concat(featureTags), envTags)
  );
  debug(
    `Feature: ${featurePath}, featureShouldRun: ${featureShouldRun}, taggedScenarioShouldRun: ${taggedScenarioShouldRun}`
  );
  if (featureShouldRun || taggedScenarioShouldRun) {
    featuresToRun.push(featurePath);
  }
});
```
It would probably be something analogous to taggedScenarioShouldRun. 

Let me know if you would be willing to include this as a part of this PR :)

2021-07-16 10:27 UTC, rkrisztian commented
> No test would actually run [...]

In my experience, it is still the last Example that runs, regardless of what tags I selected.

The bigger problem is every test that uses step definitions from `tags_implemention_with_env_set.js` is **useless**: this file does not exercise production code at all:

```js
let isPresentInTagsEnv;
const cypressEnvTags = Cypress.env("TAGS");

Given(/'(.+)' is in current TAGS environmental variable/, (envTagsString) => {
  isPresentInTagsEnv = RegExp(envTagsString).test(cypressEnvTags);
});

Then(/this should (not )?run/, (shouldNotRun) => {
  if (typeof cypressEnvTags !== "undefined") {
    expect(!shouldNotRun).to.equal(isPresentInTagsEnv);
  }
});
```

You can't rely on such tests, they will pass all the time given the Gherkin code was written correctly.

Additionally, all scenarios derived from the examples are named the same way:

```none
  Tags Implementation with environmental variables set only at examples level
    ✓ This scenario should run only 1 example (example #1)
    ✓ This scenario should run only 1 example (example #1)
```

A different numbering is important when the scenario name is not parameterized, although ideally we should add the parameter anyway:

```none
	Scenario Outline: This scenario should <result>
```

But the numbering is still off:

```none
  Tags Implementation with environmental variables set only at examples level
    ✓ This scenario should should run (example #1)
    ✓ This scenario should should not run (example #1)
```

2021-07-20 16:57 UTC, rkrisztian commented
For the upcoming weeks I have more capacity to work on all the issues with the multiple Examples sections (including this one). So review for my PR in time is appreciated. :)

2021-07-21 08:07 UTC, lgandecki commented
@MateuszNowosad do you think you'd find a moment to take a look at this again?

2021-07-21 17:19 UTC, MateuszNowosad commented
> @MateuszNowosad do you think you'd find a moment to take a look at this again?

I will try to take a look at this and new @rkrisztian's PR on the weekend.

2021-07-25 21:21 UTC, MateuszNowosad commented
@rkrisztian 

I disagree with 

> > No test would actually run [...]
> 
> In my experience, it is still the last Example that runs, regardless of what tags I selected.

If that's the case, that's an unrelated issue. I reevaluated my previous comment and still stand by the requested changes because the current behavior diverges from expectations. The takeaway from my previous comment is that when someone is using TAGS in the command line like in the example `cypress-tags.js` won't actually recognize that there are some tests that need to run in this file at all.

But I partially agree with 

> The bigger problem is every test that uses step definitions from tags_implemention_with_env_set.js is useless

After digging down on `tags_implemention_with_env_set.js` I agree that tests present in this PR don't fulfill their purpose. This is because that file only really makes sense in the context of the original tests that it was written for. This misunderstanding came from the naming. This PR would require some changes to the tests/step definitions. 

As for your newest PR, I've left a separate comment there but it seems to be good.

I don't know if I will be able to dedicate the time this week to fix the aforementioned issues but maybe;
As to not burden the author of this PR we could merge this as if there was nothing wrong with it and then make a new PR that fixes the missing test and improves `cypress-tags.js` since those aren't critical and shouldn't break anything with the current usages. Essential parts of this PR work correctly and it fixes the problem that it was supposed to fix. What would be your take on this situation @lgandecki?

2021-07-26 01:23 UTC, rkrisztian commented
@MateuszNowosad , sure, let's merge this PR first. For the problem I was experiencing, I will just recheck it.

2021-07-26 10:54 UTC, merged

2021-07-26 10:54 UTC, lgandecki commented
I've merged it as a feat instead of fix, to not introduce possibly a breaking change in a patch release.

2021-07-26 11:05 UTC, lgandecki commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/cypress-cucumber-preprocessor/v/4.2.0)
- [GitHub release](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/releases/tag/v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-09-16 01:08 UTC, bobmccracken commented on lib/createTestFromScenario.js
> +            shouldRun: shouldRunExamples,
@Sonaryr @MateuszNowosad @lgandecki This line introduced the regression in #612. This `shouldRun` does not consider `@focus`.

`shouldRun` is previously set [here](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/createTestsFromFeature.js#L31), but this overwrites it.